Feature: preview optimize
HcySunYang/vuese pull request #205
Opened 2020-11-27 01:57 UTC by screetBloom

<br>

### 1.Steps to reproduce：
- currently, vuese uses carlo to preview 
- Unfortunately, Carlo is no longer maintained , And it doesn't work as we expect In the new version of chrome

**Some error messages :** 👇
![image](https://user-images.githubusercontent.com/22092110/100336109-bb01cf00-3010-11eb-8ca1-f04246ae9e4f.png)

<br>

**Preview is no longer available in new versions of chrome :**
![image](https://user-images.githubusercontent.com/22092110/100335983-9279d500-3010-11eb-8d3e-5b74dcc2a80e.png)

<br>
<br>
<br>

### 2.My Solution to the Problem:
- Use puppeteer-core instead of Carlo （Carlo internally dependent on puppeteer-core ）
- The detailed code can be seen in this pr

#### 2.1 source code
``` shell
<template>
  <div>
    
    <slot name="header">
      
      <th>title</th>
    </slot>
  </div>
</template>

<script>
// This is a description of the component
export default {
  name: 'MyComponent2',
  props: {
    // The name of the form, up to 8 characters
    name: {
      type: [String, Number],
      required: true,
      validator () {}
    }
  },
  methods: {
    // @vuese
    // Used to manually clear the form
    clear () {
      // Fire when the form is cleared
      // @arg The argument is a boolean value representing xxx
      this.$emit('onclear', true)
    }
  }
}
</script>
```

<br>
<br>

#### 2.2 Open preview page: 
``` JS
vuese preview ./src/components/test.vue
```
![image](https://user-images.githubusercontent.com/22092110/100356388-20b08400-302e-11eb-9686-e652fdffd43e.png)

<br>
<br>

#### 2.3 hot update
``` JS
  name: 'MyComponent2',    =>    name: 'MyComponent3'
```
![image](https://user-images.githubusercontent.com/22092110/100356610-6bca9700-302e-11eb-99d7-1979850da576.png)

<br>
<br>
<br>

### 3. Why set package.json's resolutions: 
- fsevent will cause 「node-gypd」 errors under different node versions. eg. Node.js 12.x
- The most common version used in the project is 1.2.7, but 「node-gyp」 can be solved by upgrading to 1.2.9.
- see this issue: https://github.com/fsevents/fsevents/issues/278

<br>
<br>
<br>

2020-11-27 02:30 UTC, IWANABETHATGUY requested changes

2020-11-27 02:30 UTC, IWANABETHATGUY commented on packages/declarations.d.ts
> +declare module 'puppeteer-core'
npm install --save @types/puppeteer-core, try this .
declare module is the just a workaround.

2020-11-30 15:10 UTC, screetBloom commented
I made a few changes
- Update the minor version of jest（This jest version is also same to jest in  Vue CLI）

<br>
<br>

**Why**
- The current jest version was chosen two years ago, And the upgrade will have no impact on our existing logic and will solve [some dependencies problem of the jest](https://github.com/facebook/jest/issues/8490)
- we don't need to set the resolution in package.json to solve the fsevent1.2.7 「node-gypd」 errors 

<br>

 I have tested in detail .  `yarn run test`, ` yarn build` and the feature are all runs without problems

2020-11-30 15:24 UTC, IWANABETHATGUY approved these changes

2020-11-30 15:25 UTC, IWANABETHATGUY commented
LGTM!

2020-11-30 15:26 UTC, merged